"""
Day 03: Loops + Pattern Thinking (for loops, range, and iteration patterns)

Author: Drawts

Description: Loops automate repetitive tasks by iterating through sequences like lists or numerical intervals generated by the range() function. 
By combining loops with conditional logic, you can process each item individually to perform calculations or filter data based on specific rules.

Quick Summary of range()
range(stop): Starts at 0, ends one before the stop value.

range(start, stop): Starts at your specific number, ends one before the stop value.

range(start, stop, step): Controls the jump between numbers (e.g., every 2nd number).

"""

# Core Concepts


# 1 - for Loop (fundamental)
for i in range(5):
    print(i)

"""
This means:

Start at 0

Stop before 5

Step by 1 """


# 2 - Looping Through Lists
names = ["Mike", "Ana", "Luis"]

for name in names:
    print(name)

# You are not looping numbers — you are looping values.


# 3 - Range
range()
range(5)        # 0 → 4
range(1, 6)     # 1 → 5
range(0, 10, 2) # 0,2,4,6,8


# 4 - Loop + Condition (this is where thinking starts)
numbers = [1, 2, 3, 4, 5]

for number in numbers:
    if number % 2 == 0:
        print(number, "is even")


# Take a knowledge quiz (Python Loops and Iteration) here: https://gemini.google.com/share/4e4d37d22108

